
/**
 * @todo: describe the class
 */
public class BlowfishException extends Exception
{

	private static final long serialVersionUID = 1L;

	public BlowfishException(String p0)
	{
		super(p0);
	}

	public BlowfishException()
	{
		super();
	}

}

/*
 * This class is autogenerated by ClassWizard, written by Joachim Nilsson in April/May 2001.
 * This software is provided "as is" with no warranty of any kind.
 */

